# Site settings
title: A grammar-book treebank of Turkish
baseurl: "/gk-treebank"
url: "https://coltekin.github.io/gk-treebnak/"
github_username:  coltekin
encoding: utf-8
future: true

markdown: kramdown
# don't change the following; coderay will break the embedded
# # annotations.
kramdown:
  enable_coderay: false
